Henrique Duran - TR031159
Vinicius Cesar de Deus - TR030624


"Server=tcp:moove-dl-qas-sql-server.database.windows.net,1433;Initial Catalog=moove_db_01;Persist Security Info=False;User ID=sqladm;Password={your_password};"
 + "MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
 
 
 Aprenda a fazer um bot com Uipath (Robotic Process Automation)
 
 
Levantar as integrações do RFC -> Paula hoje as 16
Levantar os responsaveis das integrações 
Fazer o desenho das integrações
Avaliar a possibilidade da dll da calculadora rodar no ambiente cloud do SAP -> Naasson hoje



I wonder if your binary is compatible with Linux 64-bit operating system?

Moove: Demo Jira
06/07
15 - 16
meet.google.com/jhd-hdwj-qke 